input {
  # Mở cổng đón khách từ Filebeat
  beats {
    port => 5044
  }
}

filter {
  # Tạm thời chưa cần filter phức tạp, ta chỉ cần gắn thêm 1 tag để biết log đã đi qua Logstash
  mutate {
    add_tag => [ "processed_by_logstash" ]
  }
}

output {
  # In toàn bộ dữ liệu nhận được ra màn hình Docker Console để check
  stdout {
    codec => rubydebug
  }
}