services:
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: log-monitor-db
  #   environment:
  #     POSTGRES_DB: log_monitor_db
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password123
  #   ports:
  #     - "5432:5432"

  # redis:
  #   image: redis:7-alpine
  #   container_name: log-monitor-redis
  #   ports:
  #     - "6379:6379"

  # Sử dụng KRaft mode
  # Tìm hiều Schema Registry (confluentinc/cp-kafka)
  kafka:
    image: apache/kafka:4.2.1
    container_name: kafka-kraft
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      # listener lắng nghe trên mọi dải IP nội bộ của mạng Docker
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9092:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
  #   container_name: log-monitor-es
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false # Tắt để dev cho nhanh, bật lại khi lên prod
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.10.2
  #   container_name: log-monitor-kibana
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
