input {
  beats {
    port => 5044
  }
}

filter {
  # Parse chuỗi JSON thô trong log thành các trường dữ liệu cụ thể
  json {
    source => "message"
  }
  
  # Bốc tách tag môi trường do Filebeat gắn vào
  mutate {
    add_field => { "environment" => "%{[fields][env]}" }
  }
}

output {
  # 1. Lưu trữ toàn bộ log vào Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "sys-logs-%{environment}-%{+YYYY.MM.dd}"
  }

  # 2. Nếu là log lỗi, bắn Webhook trực tiếp sang alert-service (Spring Boot)
  if [logLevel] == "ERROR" or [logLevel] == "CRITICAL" {
    http {
      url => "http://host.docker.internal:8082/api/v1/alerts/webhook"
      http_method => "post"
      format => "json"
    }
  }

  # In ra console của Docker để tiện theo dõi lúc phát triển
  stdout {
    codec => rubydebug
  }
}