filebeat.inputs:
  - type: filestream
    enabled: true
    # Trỏ vào thư mục log (đường dẫn này là đường dẫn BÊN TRONG container Filebeat)
    paths:
      - /var/log/my-app/*.log

    # Đánh dấu log này đến từ môi trường DEV
    fields:
      env: dev
      app_name: collector-service
    fields_under_root: true

# Chuyển tiếp dữ liệu sang Logstash
output.logstash:
  hosts: ["logstash:5044"]